"""Scribe — writes deductions back into the DataHub graph via MCP mutation tools.

Every write is marked as AI-generated with its evidence trail. Ownership is
proposed (or applied with a distinct type) rather than silently overwritten.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone

from .deduce import Deduction
from .investigate import EvidenceBundle
from .mcp_client import DataHubMCP

AI_MARK = "\n\n---\n*🕵️ Generated by [Sherlock](https://github.com/ChenyiHuang-1/datahub-curator-agent), the metadata detective. Deduced from lineage, schema and query evidence — see the linked case report.*"


@dataclass
class WriteReceipt:
    actions: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def note(self, msg: str) -> None:
        self.actions.append(msg)

    def err(self, msg: str) -> None:
        self.errors.append(msg)


def write_back(
    mcp: DataHubMCP,
    evidence: EvidenceBundle,
    deduction: Deduction,
    min_confidence: float = 0.5,
    dry_run: bool = False,
) -> WriteReceipt:
    r = WriteReceipt()
    urn = evidence.case.urn

    if deduction.confidence < min_confidence:
        r.note(f"skip writes: confidence {deduction.confidence:.2f} < {min_confidence}")
        return r

    # 1. table description
    if deduction.table_description and "description" in " ".join(evidence.case.missing):
        if dry_run:
            r.note(f"[dry-run] would set table description ({len(deduction.table_description)} chars)")
        else:
            try:
                mcp.call(
                    "update_description",
                    entity_urn=urn,
                    operation="replace",
                    description=deduction.table_description + AI_MARK,
                )
                r.note("table description written")
            except Exception as e:
                r.err(f"table description failed: {e}")

    # 2. column descriptions
    written_cols = 0
    for fp, desc in deduction.column_descriptions.items():
        if dry_run:
            written_cols += 1
            continue
        try:
            mcp.call("update_description", entity_urn=urn, column_path=fp, operation="replace", description=desc)
            written_cols += 1
        except Exception as e:
            r.err(f"column {fp} failed: {str(e)[:120]}")
    if written_cols:
        r.note(f"{'[dry-run] would write' if dry_run else 'wrote'} {written_cols} column descriptions")

    # 3. PII tags
    pii_fields = [p.get("field") for p in deduction.pii_suspects if p.get("field")]
    if pii_fields:
        if dry_run:
            r.note(f"[dry-run] would tag {len(pii_fields)} columns as PII-Suspect: {pii_fields}")
        else:
            for f in pii_fields:
                try:
                    mcp.call(
                        "add_tags",
                        tag_urns=["urn:li:tag:PII-Suspect"],
                        entity_urns=[urn],
                        column_paths=[f],
                    )
                except Exception as e:
                    r.err(f"PII tag {f} failed: {str(e)[:120]}")
            r.note(f"tagged {len(pii_fields)} columns PII-Suspect")

    # 4. owner suggestion — recorded in the case report rather than force-set;
    #    direct add_owners only when explicitly enabled.
    if deduction.inferred_owner:
        r.note(f"owner deduced: {deduction.inferred_owner} (recorded in case report)")

    # 5. case report document
    report = render_case_report(evidence, deduction, r)
    if dry_run:
        r.note("[dry-run] would save case report document")
    else:
        try:
            mcp.call(
                "save_document",
                document_type="Analysis",
                title=f"Sherlock Case Report: {evidence.case.name}",
                content=report,
                related_assets=[urn],
            )
            r.note("case report saved to graph")
        except Exception as e:
            r.err(f"save_document failed: {e}")

    return r


def render_case_report(evidence: EvidenceBundle, d: Deduction, receipt: WriteReceipt) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# 🕵️ Case Report: {evidence.case.name}",
        "",
        f"- **URN**: `{evidence.case.urn}`",
        f"- **Investigated**: {ts}",
        f"- **Was missing**: {', '.join(evidence.case.missing)}",
        f"- **Confidence**: {d.confidence:.0%}",
        "",
        "## Deduced purpose",
        d.table_description or "_no deduction_",
        "",
        "## Deduction chain",
        d.reasoning or "_none_",
        "",
    ]
    if d.inferred_owner:
        lines += ["## Suggested owner", f"`{d.inferred_owner}` — inferred from query/lineage evidence. A human should confirm before assignment.", ""]
    if d.pii_suspects:
        lines += ["## ⚠️ PII suspects"] + [f"- `{p.get('field')}`: {p.get('reason')}" for p in d.pii_suspects] + [""]
    if d.column_descriptions:
        lines += ["## Column descriptions written"] + [f"- `{k}`: {v}" for k, v in d.column_descriptions.items()] + [""]
    lines += ["## Actions taken"] + [f"- {a}" for a in receipt.actions]
    if receipt.errors:
        lines += ["## Errors"] + [f"- {e}" for e in receipt.errors]
    lines += ["", "*Filed by Sherlock, the metadata detective agent.*"]
    return "\n".join(lines)
